################################
##### Server Configuration #####
################################
server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api
    encoding:
      force: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4
  shutdown: graceful

################################
##### Spring Configuration #####
################################
spring:
  application:
    name: task-manager-api
  profiles:
    active: ${APPLICATION_ENVIRONMENT}
  main:
    banner-mode: off
  mvc:
    converters:
      preferred-json-mapper: gson
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:task_manager}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:P@ssw0rd}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true

###################################
##### SpringDoc Configuration #####
###################################
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
